name: Coverage-Test
on:
  push:
jobs:
  test-project:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.0

      - name: Build Project
        uses: threeal/cmake-action@v2.0.0

      - name: Test Project
        uses: threeal/ctest-action@v1.1.0

      - name: Check Test Coverage
        uses: threeal/gcovr-action@v1.1.0
        